### ISSUE TITLE
能否告知swcaffe的安装方法？

### ISSUE THREAD

**Issue by Gradie** [feifeibear/SWCaffe#1]
您好！对这方面安装不是很清楚，swcaffe文件夹已经在远端目录了，请问该怎么安装和使用swcaffe？不胜感激！

**Comment by feifeibear** [comment]
Readme.sw里面有说明，你需要thirdparty作为依赖。你可以向无锡超算中心人工智能部申请拷贝这些依赖到你的自己目录。
